on:
  workflow_dispatch:

jobs:
  xxx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - run: npm ci
        working-directory: ide
