name: Release
on:
  schedule:
    - cron: "0 0 * * *" # midnight UTC

  workflow_dispatch:

  push:
    branches:
      - release

jobs:
  build_server:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            code-target: linux-x64
          - os: macos-latest
            code-target: darwin-arm64
    name: dist (${{ matrix.code-target }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Use OCaml
        with:
          ocaml-compiler: 4.14.0
          dune-cache: true
          cache-prefix: v1-${{ matrix.os }}
        env:
          OPAMLOCKED: locked
        uses: ocaml/setup-ocaml@v2

      - run: opam install . --deps-only --locked

      - run: LINKING_MODE=static opam exec -- dune build --profile=release

      - run: npm ci
        working-directory: ide

      - name: Copy server to bundle
        run: |
          cp _build/default/bin/main.exe ide/whycode
          cp -R _opam/lib/why3 ide/why-lib
          cp -R _opam/share/why3 ide/why-data

      - name: Package
        run: npx vsce package -o "../whycode-${{ matrix.code-target }}.vsix"
        working-directory: ide

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist-${{ matrix.code-target }}
          path: ./whycode-${{ matrix.code-target }}.vsix

  # publish:
  #   needs: build_server
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release
  #       uses: softprops/action-gh-release@v1